{
 "title": "JMeter статистика",
 "description": "Панель показывает онлайн и историческую статистику по запускам",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "profile",
    "label": "Профиль",
    "query": "SHOW TAG VALUES FROM \"requestsRaw\" WITH KEY = \"testName\""
   },
   {
    "name": "runid",
    "label": "Запуск",
    "query": "SHOW TAG VALUES FROM \"requestsRaw\" WITH KEY = \"runId\" WHERE \"testName\" =~ /^$profile$/"
   },
   { "name": "aggregation", "label": "Аггрег.", "query": "1,10,30,60,600,1800,3600" },
   {
    "name": "request",
    "label": "Операция для детализации",
    "query": "SHOW TAG VALUES FROM \"requestsRaw\" WITH KEY = \"requestName\" WHERE \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ "
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "content": "<h3 style=\"text-align: center;\"><em>Статистика по <span style=\"color: #00ccff;\"><strong>всем операциям</strong></span></em></h3>"
  },
  {
   "title": "Успешных",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "measurement": "virtualUsers",
     "query": "SELECT 1 - sum(\"errorCount\")/sum(\"points\") FROM \"requestsRaw\" WHERE \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND \"requestName\"=~ /(send|block|request)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "finishedThreads" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Единичных документов",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "virtualUsers",
     "query": "SELECT  sum(\"points\") FROM \"requestsRaw\" WHERE \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND  \"requestName\" =~ /send/ and $timeFilter",
     "select": [
      [
       { "params": [ "finishedThreads" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "nodeName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Пакетов документов",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "virtualUsers",
     "query": "SELECT  sum(\"points\") FROM \"requestsRaw\" WHERE \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND \"requestName\" =~ /block/ and $timeFilter",
     "select": [
      [
       { "params": [ "finishedThreads" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "nodeName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Запросов",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "virtualUsers",
     "query": "SELECT  count(\"responseTime\") FROM \"requestsRaw\" WHERE \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND \"requestName\" =~ /request/ and $timeFilter",
     "select": [
      [
       { "params": [ "finishedThreads" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "nodeName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Неуспешных",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "measurement": "virtualUsers",
     "query": "SELECT sum(\"errorCount\")/sum(\"points\") FROM \"requestsRaw\" WHERE \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND \"requestName\"=~ /(send|block|request)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "finishedThreads" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Нагрузка",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Потоки",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualUsers",
     "query": "SELECT mean(\"startedThreads\") FROM \"virtualUsers\" WHERE \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "startedThreads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Интенсивность",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT  sum(\"points\")/$aggregation FROM \"requestsRaw\" WHERE \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND \"requestName\"=~ /(send|block|request)/ AND $timeFilter  GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Метрики",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "SELECT sum(points) as \"Total\",count(points) as \"TotalRecs\", sum(points)/count(points) as \"Compress\", mean(responseTime)/1000 as \"AvgResp\", min(responseTime)/1000 as \"MinResp\",max(responseTime)/1000 as \"MaxResp\", percentile(responseTime, 90)/1000 as \"90perc\",percentile(responseTime, 95)/1000 as \"95perc\",percentile(responseTime, 97)/1000 as \"97perc\",percentile(responseTime, 99)/1000 as \"99perc\", sum(errorCount) as \"Errors\", (sum(errorCount)/sum(points)) as \"ErrorRate\" FROM \"requestsRaw\"  WHERE  \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND $timeFilter GROUP BY requestName",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "content": "<h3 style=\"text-align: center;\"><em>Детальная информация по операции <span style=\"color: #00ccff;\"><strong>\"[[request]]\"</strong></span></em></h3>"
  },
  {
   "title": "Интенсивность",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Интенсивность",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT sum(\"points\")/$aggregation FROM \"requestsRaw\" WHERE  \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND \"requestName\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Успешных",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 20 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "SELECT 1 - sum(\"errorCount\")/sum(\"points\") FROM \"requestsRaw\" WHERE  \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND $timeFilter AND \"requestName\" =~ /^$request$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Всего операций",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "requestsRaw",
     "query": "SELECT sum(\"points\") FROM \"requestsRaw\" WHERE  \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND \"requestName\" =~ /^$request$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  {
   "title": "Неуспешных",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "SELECT sum(\"errorCount\")/sum(\"points\") FROM \"requestsRaw\" WHERE  \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND $timeFilter AND \"requestName\" =~ /^$request$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Время отклика",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Среднее",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT mean(\"responseTime\") FROM \"requestsRaw\" WHERE  \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND \"requestName\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "90 perc",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT percentile(\"responseTime\", 90) FROM \"requestsRaw\" WHERE  \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND \"requestName\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "95 perc",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT percentile(\"responseTime\", 95) FROM \"requestsRaw\" WHERE  \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND \"requestName\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "97 perc",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"responseTime\", 97) FROM \"requestsRaw\" WHERE  \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND \"requestName\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "99 perc",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT percentile(\"responseTime\", 99) FROM \"requestsRaw\" WHERE  \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND \"requestName\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "Максимальное",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT max(\"responseTime\") FROM \"requestsRaw\" WHERE  \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND \"requestName\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 28 } },
  {
   "title": "Интенсивность ошибок",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "errors / s" }
   ],
   "targets": [
    {
     "alias": "Ошибок в сек.",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requestsRaw",
     "query": "SELECT sum(\"errorCount\")/$aggregation FROM \"requestsRaw\" WHERE  \"testName\" =~ /^$profile$/ AND \"runId\" =~ /^$runid$/ AND \"requestName\" =~ /^$request$/ AND $timeFilter GROUP BY time([[aggregation]]s) fill(null)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
     ]
    }
   ]
  }
 ]
}